name: Release Action
on: workflow_dispatch

permissions: write-all

env:
  PROJECT_NAME: MintyEngine

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android
            os: macos-15
            buildArgs: "android -final -D officialBuild"
            artifactName: Android
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Zip Artifacts
        run: |
           zip -r Android.zip Android/
           

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Template"
          tag_name: "0.7.3"
          make_latest: false
          files: |
            
            Android.zip
            
